# variable 

Variable is an identifer used to store a value in program.

variables allows us to store different type of data, such letters,numbers and special charcters.

## variables rules:
-We can use letters,numbesr and underscore('_') in variables names.

-A variable name must start with letters or underscore(_)

-Variable name cannot start with numbers

-python is case-sensetive, so 'name' and 'Name' are different variables.

## step 2 - Demostrate the concept

variables 
name="dhinesh"

`name` is a variable and `"dhinesh"` is a value stored in the variable.

number=10

`number` is a variable and `10` is a value stored in the variable.
   

In [2]:
name="dhinesh" 
age=23
height=5.4
city="salem"

print("Name:",name)
print("Age:",age)
print("Height:",height)
print("City:",city)

Name: dhinesh
Age: 23
Height: 5.4
City: salem


## Code Explanation

In this program, I created four variables: `name`, `age`, `height`, and `city`.

The `name` and `city` variables store string values.

The `age` variable stores an integer value, and the `height` variable stores a float value.

I used the `print()` function to display all the variable values in the console.

# Data Types

A data type tells Python what type of value is stored in a variable.

Python has different built-in data types for storing different kinds of data.

## Common Python Data Types

- `int` – used to store whole numbers.

- `float` – used to store decimal numbers.

- `str` – used to store text. A string can be enclosed within single quotes (`' '`) or double quotes (`" "`).

- `bool` – used to store `True` or `False` values.

In [3]:
name="dhineshkumar"
age=22
height=5.5
is_employee=True
print(name,type(name))
print(age,type(age))
print(height,type(height))
print(is_employee,type(is_employee))

dhineshkumar <class 'str'>
22 <class 'int'>
5.5 <class 'float'>
True <class 'bool'>


## Code Explanation

In this program, I created four variables: `name`, `age`, `height`, and `is_employee`.

- The `name` variable stores a string value.
- The `age` variable stores an integer value.
- The `height` variable stores a decimal value.
- The `is_employee` variable stores a Boolean value.

I used two functions: `print()` and `type()`.

- The `print()` function displays the values in the console.
- The `type()` function tells us the data type of a value.

# Type Casting

Type casting means converting a value from one data type to another data type

## Type casting built-in function

`int()`- converts a value into an integer.

`float()`- converts a value into a floating-point number

`bool()`- converts a value into a boolean values

`str()` - converts a value into a string value.`

# Step 2 – Demonstrate the Concept

## Real-World Example

Suppose a student gets a mark of `89.5`.

The mark is stored as a float because it contains a decimal value.

If the system requires a whole-number mark, we can convert the float value into an integer using `int()`.

For example:

89.5 → 89


name="dhinesh"
age=24
float_mark=89.5

#folat to integer
int_mark=int(float_mark)

#integer to float
float_age=float(age)

#integer to string
str_age=str(age)

print("original values")
print(name,type(name))
print(age,type(age))
print(float_mark,type(float_mark))

print("\nconvert values")

print(int_mark,type(int_mark))
print(float_age,type(float_age))
print(str_age,type(str_age))



In [15]:
name="dhinesh"
age=24
float_mark=89.5

#folat to integer
int_mark=int(float_mark)

#integer to float
float_age=float(age)

#integer to string
str_age=str(age)

print("original values")
print(name,type(name))
print(age,type(age))
print(float_mark,type(float_mark))

print("\nconvert values")

print(int_mark,type(int_mark))
print(float_age,type(float_age))
print(str_age,type(str_age))



original values
dhinesh <class 'str'>
24 <class 'int'>
89.5 <class 'float'>

convert values
89 <class 'int'>
24.0 <class 'float'>
24 <class 'str'>


## Code Explanation

In this program, I created three variables with different values.

I converted the float value `89.5` into an integer using `int()`.

I converted the integer value `24` into a float using `float()`.

I converted the integer value `24` into a string using `str()`.

I used the `print()` function to display the values and the `type()` function to check their data types.


# Operators

Operators is a symbols or keywords used to perform operations on value and variabes

## Types of Operators

- Arithmetic Operators
- Assignment Operators
- Comparison Operators
- Logical Operators

### Arithmetic Operators

Arithmetic operators are used to perform mathematical operations.

Examples: `+`, `-`, `*`, `/`, `%`, `//`, `**`

### Assignment Operators

Assignment operators are used to assign or update values in variables.

Examples: `=`, `+=`, `-=`, `*=`, `/=`

### Comparison Operators

Comparison operators are used to compare two values.

Examples: `==`, `!=`, `>`, `<`, `>=`, `<=`

### Logical Operators

Logical operators are used to combine or evaluate conditions.

Examples: `and`, `or`, `not`



In [1]:
# Student marks
python_mark=60
sql_mark=80
math_mark=90

# Calculate total marks
total=python_mark+sql_mark+math_mark

# Calculate average marks
average=total/3

# Passing average
passing_mark=50

# Check pass or fail
is_pass=average>=passing_mark

# Display the results
print("Python Mark:",python_mark)
print("SQL Mark:",sql_mark)
print("Math Mark:",math_mark)

print("Total Marks:",total)
print("Average Marks:",average)
print("Pass:",is_pass)

if is_pass:
    print("Result: Pass")
else:
    print("Result: Fail")


Python Mark: 60
SQL Mark: 80
Math Mark: 90
Total Marks: 230
Average Marks: 76.66666666666667
Pass: True
Result: Pass


# Input

-Information or data provided to a Python program by the user.

input()

    The input() function is used to get data from the user.

In [2]:
name=input("Enter your name:")
age=input("Enter your age:")

print("Name:",name)
print("Age:",age)

Enter your name: dhineshkumar
Enter your age: 22


Name: dhineshkumar
Age: 22


# Output

-Output is the information or data produced by a Python program and displayed on the console.

print()

    The print() function is used to display values on the console.

In [3]:
name="dhineshkumar"
age=22
city="salem"
print("Name:",name)
print("age:",age)

Name: dhineshkumar
age: 22


# Comments

-Comments are notes written in a Python program to explain the code. Python does not execute comments.

Comments Types

    Single-line comments
    Multi-line comments


In [4]:
# This is a Single-line comment
print("Hello")

# This is a multi-line comment
address="""
30,Tharamangalam
omalur,
salem-646401"""
print(address)



Hello

30,Tharamangalam
omalur,
salem-646401


# Control Flow

## if / elif / else

### if

-if checks a condition. If it is true, the code inside if runs.

### elif

-elif checks another condition when the previous condition is false.

### else

else runs when all the previous conditions are false.

In [6]:
age = 16

if age >= 18:
    print("Eligible to vote")
elif age >= 13:
    print("Teenager - Not eligible to vote")
else:
    print("Child - Not eligible to vote")

Teenager - Not eligible to vote


# For Loop

A for loop is used to repeat a block of code for each item in a sequence.

In [7]:
#Print numbers from 1 to 5.

for number in range(1, 6):
    print(number)

1
2
3
4
5


# While Loop

A while loop repeatedly executes a block of code as long as the condition is true.

In [8]:
count=1

while count<= 5:
    print(count)
    count+=1

1
2
3
4
5


# break

The break statement immediately stops the loop and exits it.


In [9]:
for i in range(1,6):
    if i==3:
        break
    print(i)

1
2


# Continue

The continue statement skips the current iteration and moves to the next iteration.

In [10]:
for i in range(1,6):
    if i==4:
        continue
    print(i)

1
2
3
5


# Pass

The pass statement does nothing. It acts as a placeholder.

In [11]:
for i in range(1,6):
    if i==3:
        pass
    print(i)

1
2
3
4
5


# Collections

## List

-Lists are used to store multiple items in a single variable.

-List items are ordered and allow duplicate values.

-List items are indexed, the first item has index [0], the second item has index [1] etc.

-Lists are mutable, so we can change their values.

-Lists are created using square brackets [].

## Real-time example:

In an online shopping application, a customer's selected products can be stored in a list.

["Laptop","Mouse","Keyboard"]

In [12]:
products=["Laptop","Mouse","Keyboard","Mouse"]

print(products)
print(products[0])

products[1]="Monitor"
print(products)

['Laptop', 'Mouse', 'Keyboard', 'Mouse']
Laptop
['Laptop', 'Monitor', 'Keyboard', 'Mouse']


# Tuple

-Tuples are used to store multiple items in a single variable

-Tuples are immutable, so their values cannot be changed after creation.

-Tuples allow duplicate values

-Tuples can store different data types.

-Tuples are usually created using parentheses ()

## Real-time example:

A company's employee ID details can be stored in a tuple because the stored information should not be changed.

(101,"Dhinesh","AI/ML Engineer")

In [17]:
employee=(101,"Dhinesh","AI/ML Engineer")

print(employee)
print(employee[1])


(101, 'Dhinesh', 'AI/ML Engineer')
Dhinesh


## Step 1 – Understand the Concept

### Set

A set is a collection used to store unique values. Sets are unordered and mutable, so items can be added or removed.

-Sets do not allow duplicate values

-Set items are not accessed using index numbers.

-A set can contain different data types.

-Sets are created using curly brackets {}.

## Step-2 Demonstrate the Concept

Think of a college attendance system. If the same student is marked present twice, we need to keep the student only once.

101,102,101,103

A set stores only the unique student IDs:

101,102,103


In [18]:
student_ids={101,102,101,103}

print(student_ids)

student_ids.add(104)

print(student_ids)

{101, 102, 103}
{104, 101, 102, 103}


### Explanation

student_ids is a set.

The duplicate value 101 is automatically removed.

add() adds a new value to the set.

This demonstrates that sets store unique values and can be changed.

## Step 1 – Understand the Concept

### Dictionary

Dictionaries are used to store data values in key:value pairs.

-Each key identifies a value

-Keys must be unique.

-Dictionaries are mutable, so values can be changed.

-A dictionary is created using curly brackets {}

## Step-2 Demonstrate the Concept

The student record. A student has different details such as name, age, and course.

Name → Dhinesh

Age → 21

Course → Python

## Implementation & Explanation

In [19]:
student={
    "name":"Dhinesh",
    "age":21,
    "course":"Python"
}

print(student["name"])

student["age"]=22

print(student)

Dhinesh
{'name': 'Dhinesh', 'age': 22, 'course': 'Python'}


## Step 1 – Understand the Concept

### List Comprehension

List comprehension is a short way to create a new list from an existing sequence.

## Step-2 Demonstrate the Concept

shopping application. Suppose we have product prices and want to create a new list containing only prices above ₹500.

100, 750, 300, 1200

The new list will contain:

750, 1200

## Implementation & Explanation


In [20]:
prices=[100,750,300,1200]

expensive=[price for price in prices if price>500]

print(expensive)

[750, 1200]


-for price in prices checks each price.

-if price>500 selects prices above 500.

-The selected values are stored in the new list expensive.

-print the expensive

## Step 1 – Understand the Concept

### Dictionary Comprehension

Dictionary comprehension is a short and simple way to create a new dictionary using a loop.

Normally, we use a for loop to create a dictionary. With dictionary comprehension, we can do the same thing in a single line.

## Step 2 – Demonstrate the Concept

We have two list of students and their marks

students=["Arun","Bala","Dhinesh"]

marks=[80,75,90]

We want to create a dictionary like:

{

    "Arun":80,
    
    "Bala":75,
    
    "Dhinesh":90
    
}


In [22]:
students=["Arun","Bala","Dhinesh"]
marks=[80,75,90]

student_marks={student:mark for student,mark in zip(students,marks)}

print(student_marks)

{'Arun': 80, 'Bala': 75, 'Dhinesh': 90}


-student → becomes the key

-mark → becomes the value

-for student,mark → takes each pair

-zip(students,marks) → connects the two lists

## Step 1 – Understand the Concept

### Function Definition

A function is a block of code that is used to perform a specific task.

A function is created using the def keyword. The code inside the function is executed when we call the function.


In [25]:
def welcome():
    print("Welcome to Python")

welcome()

Welcome to Python


### Explanation

The welcome() function is created using the def keyword.

The function contains a print() statement that displays a welcome message.

The welcome() statement calls the function and executes the code inside it.

### Arguments

Arguments

Arguments are the values that we pass to a function when we call the function.

Arguments are used to give input to the function

In [26]:
def greet(name):
    print("Hello",name)

greet("Dhinesh")

Hello Dhinesh


### Explanation

The greet() function is created with a parameter called name.

The name parameter receives a value when the function is called.

The greet("Dhinesh") statement passes "Dhinesh" as an argument to the function.

The function then prints the greeting message with the given name.

### Default Arguments

A default argument is a value that is already assigned to a parameter in the function definition

If we do not pass a value when calling the function, Python uses the default value.

In [28]:
def greet(name="Dhinesh"):
    print("Hello",name)

greet()
greet("Varun")

Hello Dhinesh
Hello Varun


### Explanation

The greet() function has a parameter called name with a default value of "Dhinesh".

If no argument is passed, the function uses the default value "Dhinesh".

When "Varun" is passed as an argument, the default value is replaced with "Varun".

### Keyword Arguments

Keyword arguments are arguments that are passed to a function using the parameter name.

Instead of passing values only by their position, we specify which parameter should receive each value.

In [29]:
def student(name,age):
    print(name,age)

student(name="Dhinesh",age=21)

Dhinesh 21


### Explanation

The student() function has two parameters: name and age.

The function is called using keyword arguments.

name="Dhinesh" assigns "Dhinesh" to the name parameter.

age=21 assigns 21 to the age parameter.

Keyword arguments make it clear which value is passed to each parameter.

### Variable-Length Arguments (*args, **kwargs)

Variable-length arguments are used when we don't know how many arguments will be passed to a function.

-*args 

    *args is used when we want to pass any number of positional arguments.

-**kwargs 

    **kwargs is used when we want to pass any number of keyword arguments.

In [34]:
#*args

def add_numbers(*numbers):
    total=0

    for number in numbers:
        total=total+number

    print("Total:",total)

add_numbers(10,20)
add_numbers(10,20,30)

print()

def student_details(**details):
    print(details)

student_details(name="Dhinesh",age=21,course="Python")


Total: 30
Total: 60

{'name': 'Dhinesh', 'age': 21, 'course': 'Python'}


### Explanation
*args

The *args syntax is used when a function needs to accept a variable number of positional arguments.

In the add_numbers() function, *numbers collects all the given numbers into a tuple.

The for loop goes through each number and adds it to total.

The function can accept different numbers of arguments.

## Step 1 – Understand the Concept

### Lambda Functions

-A lambda function is a small anonymous function.

-A lambda function can take any number of arguments, but can only have one expression.

## Step 2 – Demonstrate the Concept

Suppose an application needs to double a number.

In [35]:
square=lambda number:number*number

print(square(5))

25


## Step 1 – Understand the Concept

-A recursive function is a function that calls itself to solve a problem.

-The function keeps calling itself with a smaller or simpler value until it reaches a stopping condition, called the base condition

-Recursive call → the function calls itself.

-Base condition → tells the function when to stop.

Real-time example: Countdown

Suppose we want to count down from 5:

In [36]:
def countdown(number):
    if number==0:
        return

    print(number)
    countdown(number-1)

countdown(5)

5
4
3
2
1


### Explanation

The countdown() function is a recursive function because it calls itself inside the function.

The if number == 0 condition is the base condition. It stops the recursion when the number reaches 0.

The print(number) statement prints the current number.

The countdown(number - 1) statement calls the same function again with the number decreased by 1.

# Advanced Python

## iterator

An iterator is an object that allows you to access elements one by one from a collection or sequence.

-iter() → creates an iterator from an iterable.

-next() → gets the next value from the iterator.


Real-time example:

-Imagine a queue at a ticket counter:

Person 1 → Person 2 → Person 3 → Person 4

In [37]:
numbers=[10,20,30,40]

number_iterator=iter(numbers)

print(next(number_iterator))
print(next(number_iterator))
print(next(number_iterator))
print(next(number_iterator))

10
20
30
40


### Explanation

The numbers list contains four values.

The iter() function converts the list into an iterator.

The number_iterator stores the iterator object.

The next() function is used to get the next value from the iterator.

Each time next() is called, it moves to the next value in the list.

## Generators

A generator is a special type of function that produces values one at a time instead of producing all values at once.

Generators use the yield keyword.

Real-time example:

Imagine an application has 1 lakh customer records.

Instead of loading all 1 lakh records into memory:


In [39]:
def numbers():
    yield 1
    yield 2
    yield 3

result=numbers()

print(next(result))
print(next(result))


1
2


### Explanation

The numbers() function is a generator function because it uses the yield keyword.

The yield keyword returns a value one at a time and pauses the function.

The result = numbers() statement creates a generator object.

The next() function gets the next value from the generator.

The first next(result) returns 1.

The second next(result) returns 2.

The function pauses after each yield and continues from where it stopped when next() is called again.

### yield

yield is a Python keyword used in a generator function.

It is used to produce one value at a time and pause the function.

### Demonstrate the Concept

Think of a vending machine:

Request → 1 item → pause
Request → 1 item → pause
Request → 1 item → pause


In [41]:
def numbers():
    yield 10
    yield 20
    yield 30

result=numbers()

print(next(result))
print(next(result))
print(next(result))

10
20
30


### Explanation

The numbers() function is a generator function because it uses the yield keyword.

The result = numbers() statement creates a generator object.

The next() function gets the next value from the generator.

The first next(result) returns 10.

The second next(result) returns 20.

The third next(result) returns 30.

After each yield, the function pauses and continues from the next yield when next() is called again.

### Decorators

A decorator is a function that is used to add extra functionality to another function without changing the original function's code.

Real-time example:

Imagine you have a basic mobile phone.

Basic Phone
    ↓
Add Camera
    ↓
Add extra feature

In [43]:
def decorator(function):
    def wrapper():
        print("Before")
        function()
        print("After")
    return wrapper

@decorator
def hello():
    print("Hello")

hello()

Before
Hello
After


### Explanation

A decorator is used to add extra behavior to an existing function without changing its original code.

The decorator() function receives another function as an argument.

The wrapper() function adds extra code before and after the original function.

The @decorator syntax applies the decorator to the hello() function.

When hello() is called, the wrapper() function runs.

First, "Before" is printed, then the original hello() function runs, and finally "After" is printed.

### Closures

A closure is a function that remembers and uses a value from its outer function even after the outer function has finished running.


In [44]:
def create_greeting(name):
    def greeting():
        print("Hello",name)
    return greeting

hello=create_greeting("Dhinesh")

hello()

Hello Dhinesh


### Explanation

A closure is created when an inner function remembers and uses a value from the outer function.

The create_greeting() function takes name as an argument.

The inner greeting() function uses the name variable from the outer function.

The create_greeting("Dhinesh") statement creates the greeting() function and remembers the value "Dhinesh".

The hello() statement calls the returned function.

### global

global is used inside a function when we want to change a variable that belongs to the global scope

In [45]:
count=0

def increase():
    global count
    count=count+1

increase()

print(count)

1


### Explanation

The count variable is created outside the function, so it is a global variable.

The increase() function uses the global keyword to access and modify the global count variable.

Without the global keyword, Python would treat count inside the function as a local variable when assigning to it.

The count = count + 1 statement increases the value of count by 1.

After calling increase(), the value of count becomes 1.

### nonlocal

nonlocal is used inside a nested function when we want to change a variable that belongs to the outer function.


In [46]:
def counter():
    count=0

    def increase():
        nonlocal count
        count=count+1
        print(count)

    increase()
    increase()

counter()

1
2


### Explanation

The count variable is created inside the counter() function, so it belongs to the outer function.

The increase() function is an inner function.

The nonlocal keyword allows the increase() function to modify the count variable from the outer counter() function.

Each time increase() is called, the value of count increases by 1.

The increase() function is called two times, so the values 1 and 2 are printed.

### Modules

A module is a Python file that contains reusable code such as functions, variables, and classes.

Real-world example:

Think of a toolbox.

Toolbox

  ↓
  
Different tools

  ↓
  
We use the tool when needed


In [50]:
import datetime

print(datetime.date.today())

2026-09-23


### Explanation

The datetime module is imported using the import statement.

The datetime.date.today() function gets the current date.

The print() function displays the current date.

### Package

A package is a folder that contains multiple Python modules and organizes them together.

Real-world example:

Think of a school. It has different areas such as Students, Teachers, and Exams. Each area handles related information.

Similarly, a package can organize modules for students, teachers, and exams in one folder.


### Virtual Environment

A virtual environment is a separate environment used to install and manage Python packages for a specific project.

Real-world example

Think of a kitchen. Different chefs can have their own kitchens with their own ingredients and tools. Changes in one kitchen do not affect the other kitchen.

### Type Hinting

Type hinting is a way of specifying the expected data type of a variable, function parameter, or return value.

Real-World example

Think of a form. If a form has a field called Age, we expect a number. If another field is Name, we expect text.

In [52]:
name:str="Dhinesh"
age:int=25

print("Name:",name)
print("Age:",age)

def add(a:int,b:int)->int:
    return a+b

print(add(20,30))

Name: Dhinesh
Age: 25
50


### Explanation

Type hinting is used to indicate the expected data type of a variable or function parameter.

name: str indicates that name is expected to contain a string.

age: int indicates that age is expected to contain an integer.

In the add() function, a: int and b: int indicate that the parameters are expected to be integers.

-> int indicates that the function is expected to return an integer.

Type hints improve code readability and make the expected data types clear.

# Built-in Functions

### map()

map() is a built-in Python function used to apply the same function to each item in a sequence.

Real-world example:

Think of three students' marks. If we want to add 5 bonus marks to every student's mark, we can use map() to apply the same calculation to all students' marks.

In [1]:
marks=[50,60,70]

def add_bonus(mark):
    return mark+5

result=map(add_bonus,marks)

print(list(result))

[55, 65, 75]


### Explanation

The marks list contains three marks: 50, 60, and 70.

The add_bonus() function adds 5 to each mark.

The map() function applies the add_bonus() function to every value in the marks list.

The result stores the mapped values.

The list() function converts the map object into a list.

### filter()

filter() is a built-in function that selects items from an iterable based on a condition.

It checks each item one by one. If the condition is True, the item is included in the result. If it is False, the item is excluded.

Real-world example

Imagine a teacher has marks of several students and wants to find only the students who scored 50 or more. filter() can check each mark and keep only the marks that satisfy this condition.

In [2]:
marks=[40,55,30,80,65]

def passed(mark):
    return mark>=50

result=filter(passed,marks)

print(list(result))

[55, 80, 65]


### Explanation

The marks list contains different student marks.

The passed() function checks whether a mark is greater than or equal to 50.

The filter() function applies the passed() function to each mark.

Only the marks for which the condition is True are included in the result.

The list() function converts the filter object into a list.

### zip()

zip() is used to combine two or more lists item by item

Real-world example

Imagine you have a list of student names and a list of their marks. You want to connect each student with their corresponding mark.

In [3]:
students=["Arun","Bala","Dhinesh"]
marks=[80,75,90]

result=zip(students,marks)

print(list(result))

[('Arun', 80), ('Bala', 75), ('Dhinesh', 90)]


### Explanation

The students list contains student names.

The marks list contains the corresponding marks.

The zip() function combines the values from both lists based on their positions.

The first student is combined with the first mark, the second student with the second mark, and so on.

The list() function converts the zip object into a list of tuples.

### enumerate()

enumerate() is used to get both the index and the value of each item in a list.

Real-world example

Imagine a shopping list. You want to display each item along with its number, such as 1. Laptop, 2. Mouse, 3. Keyboard. enumerate() helps us get the position and item together.

In [5]:
products=["Laptop","Mouse","Keyboard"]

result=enumerate(products)

print(list(result))

[(0, 'Laptop'), (1, 'Mouse'), (2, 'Keyboard')]


### Explanation

The products list contains three product names.

The enumerate() function adds an index number to each item in the list.

By default, the index starts from 0.

The list() function converts the enumerate object into a list of tuples.

### sorted()

sorted() used to  arranges values in ascending order

Real-world example:

Imagine you have the prices of some products, but they are not arranged. You want to display them from the lowest price to the highest price. sorted() can arrange them for you.

In [6]:
prices=[500,200,800,300]

result=sorted(prices)

print(result)

[200, 300, 500, 800]


### Explanation

The prices list contains different price values.

The sorted() function sorts the values in ascending order by default.

The result stores the sorted values.

The original prices list is not changed.

The print() function displays the sorted list.

### any()

any() is used to check whether at least one item in a list or sequence is True.

-If one or more items are True → any() returns True.

-If all items are False → any() returns False.

Real-world example:

Imagine checking whether any student has scored more than 90 marks. If even one student has scored more than 90, the result is True.

In [7]:
marks=[70,85,95,60]

result=any(mark>90 for mark in marks)

print(result)

True


### Explanation

The marks list contains four marks.

The any() function checks whether at least one value satisfies the given condition.

The condition mark > 90 checks whether any mark is greater than 90.

Since 95 is greater than 90, the condition is True.

Therefore, any() returns True.

### all()

all() is used to check whether all items in a sequence are True.

If all items are True → all() returns True.
    
If even one item is False → all() returns False.

Real-world example:

Imagine checking whether all students scored 50 or more marks. If every student passed, the result is True. If even one student scored below 50, the result is False.

In [8]:
marks=[60,75,80,55]

result=all(mark>=50 for mark in marks)

print(result)

True


### Explanation

The marks list contains four marks.

The all() function checks whether all values satisfy the given condition.

The condition mark >= 50 checks whether every mark is greater than or equal to 50.

All the marks are 50 or above, so the condition is True for every value.

Therefore, all() returns True.

### isinstance()

isinstance() is used to check whether a value belongs to a particular data type.

True → if the value is of the given type.
    
False → if the value is not of the given type.

Real-world example:
    
Imagine an online shopping application receiving a product price. Before doing calculations, we can check whether the price is actually a number.

In [10]:
price=500

result=isinstance(price,int)

print(result)

True


### Explanation

The price variable stores the value 500.

The isinstance() function checks whether a value belongs to a specific data type.

Here, isinstance(price, int) checks whether price is an integer.

Since 500 is an integer, the result is True.

### id()

id() is a built-in function used to get the unique identity of an object

Real-world example:

Think of a company employee. Two employees may have the same name, but each employee has a unique employee ID. Similarly, Python objects have their own identity, which we can see using id().

In [11]:
name="Dhinesh"

print(id(name))

2253181577488


### Explanation

The name variable stores the value "Dhinesh".

The id() function returns the unique identity number of the object stored in the variable.

Here, id(name) returns the identity of the string object "Dhinesh".

The exact number may be different each time you run the program.